### PR TITLE
DO- NOT-MERGE  some more fixes

### PR DESCRIPTION
**Pull request by onano**
mdss: property

https://github.com/armani-dev/kernel_test/commit/7a3233886c0e80c7886d4c08e090ce7c60b4ebd2#diff-488b6e4d859323482e35be0ccfad596cR71

cabc:

https://github.com/armani-dev/kernel_test/commit/7a3233886c0e80c7886d4c08e090ce7c60b4ebd2#diff-5c6478e2b2839d57fb062d6391917858R422

I don't know what else might be missing, though it's a start in right direction

### CODE REVIEW

**Comment by onano** [comment]
@fefifofum any ideas why can't backlight become stable?

**Comment by onano** [comment]
we don't need that mdss change , it's already in current tag

**Comment by fefifofum** [comment]
So the cabc commit makes things better? I have to run some tests...

**Comment by onano** [comment]
yes, a bit

**Pull request closed without merging**
